# Generated by ‘nixos-generate-config’ and formatted manually
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "sd_mod"
        "rtsx_usb_sdmmc"
      ];
      kernelModules = [ ];
    };

    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/swap"; }
    ];

fileSystems."/home/plutusVM/NAS/plutus" =
  { device = "192.168.1.212:/volume2/homes/plutus";
    options = [ "x-systemd.automount" "noauto" ];
    fsType = "nfs";
  };

#  fileSystems."/home/onyx/NAS/Cardano" =
#    { device = "192.168.1.212:/volume2/Cardano";
#      options = [ "x-systemd.automount" "noauto" ];
#      fsType = "nfs";
#    };

#fileSystems."/home/plutusVM/NAS/Programming" =
#  { device = "192.168.1.212:/volume2/Programming";
#    options = [ "x-systemd.automount" "noauto" ];
#    fsType = "nfs";
#  };

}
