# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4508c421-4cb6-4b60-bcac-3915c18abdad";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B307-7565";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/23d6c9ef-5721-4e99-81e4-40d68e32e0a8"; }
    ];

fileSystems."/home/plutusVM/NAS/NASvideo" =
  { device = "192.168.1.212:/volume2/video";
    options = [ "x-systemd.automount" "noauto" ];
    fsType = "nfs";
  };

fileSystems."/home/plutusVM/NAS/Programming" =
  { device = "192.168.1.212:/volume2/Programming";
    options = [ "x-systemd.automount" "noauto" ];
    fsType = "nfs";
  };

fileSystems."/home/plutusVM/NAS/plutus" =
  { device = "192.168.1.212:/volume2/homes/plutus";
    options = [ "x-systemd.automount" "noauto" ];
    fsType = "nfs";
  };

fileSystems."/home/plutusVM/NAS/NASmusic" =
  { device = "192.168.1.212:/volume2/music";
    options = [ "x-systemd.automount" "noauto" ];
    fsType = "nfs";
  };
  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  virtualisation.virtualbox.guest.enable = true;
}
